### ISSUE TITLE
Want to reflect method type

### ISSUE THREAD

**Issue by XuJin186** [mrlacey/Rapid-XAML-Toolkit#259]
Because the MVVM framework uses the Stylet command as a method, all reflection methods need to be bound to the button, and sincere requirement generation DataGrid

**Comment by XuJin186** [comment]
Thank you

**Comment by mrlacey** [comment]
The problem with generating UI based on an MVVM Framework that maps commands to methods is that there's no way to know from the class which methods this should be done for.
My early experimentation in this area found that ViewModels often have many more methods than should be bound to the UI.
Public parameter-less methods that return void is a possible option but it doesn't allow for scenarios where parameters should be passed from the UI.

The actual requirements of what is needed here seem very tied to specific frameworks. Where something framework specific is needed it seemed more appropriate for the framework providers to do something rather rely on a generic tool.

I'm happy to hear others thoughts on this though, and am not ruling it out entirely.

**Comment by XuJin186** [comment]
Thanks for the answer,The way to expose the general view model is to bind commands that you need, and can this extension generate DataGrid?

**Comment by mrlacey** [comment]
In theory it's possible to generate a DataGrid but I haven't created the profile/mapping that supports this. Someone asked this in theory before (tracked at #209) but has been low priority on the backlog. 
I'll see if I can find some time to prioritize this.

**Comment by XuJin186** [comment]
Well, thank you

**Comment by mrlacey** [comment]
I've created a configuration that outputs a `DataGrid` like this:

**Sub-Property Output**
```xml
<controls:DataGridTextColumn Binding="{Binding $name$}" Header="$namewithspaces$" />
```

**Mapping for `ObservableCollection<T>`**
```xml
<controls:DataGrid AutoGenerateColumns="False" GridLinesVisibility="Horizontal" ItemsSource="{x:Bind ViewModel.$name$, Mode=OneWay}">
    <controls:DataGrid.Columns>$subprops$</controls:DataGrid.Columns>
</controls:DataGrid>
```

In the editor it looks like this:

![image](https://user-images.githubusercontent.com/189547/65352038-83fc8600-dbe1-11e9-823f-6493b11c7445.png)


I can then take a property like this

```cs
public ObservableCollection<SampleOrder> Source { get; }
```

which references

```cs
    public class SampleOrder
    {
        public long OrderID { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime RequiredDate { get; set; }
        public DateTime ShippedDate { get; set; }
        public string ShipperName { get; set; }
        public string ShipperPhone { get; set; }
        public double Freight { get; set; }
        public string Company { get; set; }
        public string ShipTo { get; set; }
        public double OrderTotal { get; set; }
        public string Status { get; set; }
        public char Symbol => (char)SymbolCode;
        public int SymbolCode { get; set; }
        public ICollection<SampleOrderDetail> Details { get; set; }
        public override string ToString()
        {
            return $"{Company} {Status}";
        }
        public string ShortDescription => $"Order ID: {OrderID}";
    }
```

That creates this XAML

```xml
<controls:DataGrid AutoGenerateColumns="False" GridLinesVisibility="Horizontal" ItemsSource="{x:Bind ViewModel.Source, Mode=OneWay}">
    <controls:DataGrid.Columns>
        <controls:DataGridTextColumn Binding="{Binding OrderID}" Header="Order ID" />
        <controls:DataGridTextColumn Binding="{Binding OrderDate}" Header="Order Date" />
        <controls:DataGridTextColumn Binding="{Binding RequiredDate}" Header="Required Date" />
        <controls:DataGridTextColumn Binding="{Binding ShippedDate}" Header="Shipped Date" />
        <controls:DataGridTextColumn Binding="{Binding ShipperName}" Header="Shipper Name" />
        <controls:DataGridTextColumn Binding="{Binding ShipperPhone}" Header="Shipper Phone" />
        <controls:DataGridTextColumn Binding="{Binding Freight}" Header="Freight" />
        <controls:DataGridTextColumn Binding="{Binding Company}" Header="Company" />
        <controls:DataGridTextColumn Binding="{Binding ShipTo}" Header="Ship To" />
        <controls:DataGridTextColumn Binding="{Binding OrderTotal}" Header="Order Total" />
        <controls:DataGridTextColumn Binding="{Binding Status}" Header="Status" />
        <controls:DataGridTextColumn Binding="{Binding Symbol}" Header="Symbol" />
        <controls:DataGridTextColumn Binding="{Binding SymbolCode}" Header="Symbol Code" />
        <controls:DataGridTextColumn Binding="{Binding Details}" Header="Details" />
        <controls:DataGridTextColumn Binding="{Binding ShortDescription}" Header="Short Description" />
    </controls:DataGrid.Columns>
</controls:DataGrid>
```

And when run in a UWP app looks like this.

![image](https://user-images.githubusercontent.com/189547/65351801-eacd6f80-dbe0-11e9-9356-dd86bc8414a9.png)


**Note: I recommend updating to 0.3.5 to try this as that includes a fix for editing profiles.**

Hopefully, this gives you enough to generate a data grid for your needs.

**Comment by XuJin186** [comment]
Thank you, but my attempt to download Microsoft Extensions has been unsuccessful, and whether you plan to have a feature that excludes some attributes at the time of generation because some fixed attributes do not need to be bound to the interface. I sincerely want a way to generate buttons and bind commands even if this is optional.

**Comment by XuJin186** [comment]
I also have a suggestion that I hope this extension will add shortcuts to allow developers to quickly generate XAML by selecting the attributes and then pressing the shortcuts before copying.

**Comment by mrlacey** [comment]
> Thank you, but my attempt to download Microsoft Extensions has been unsuccessful, 

How did you try to download it? There's a preview you can install from [here](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.RapidXamlPreview).
Or search in Extensions > Manage Extensions
![](https://1.bp.blogspot.com/-6MozzQiAebc/XYN8SLZdClI/AAAAAAAAKGc/bP0ZYMKQ-SMYEt3SBqMbxNXHIAoSzLrIwCLcBGAsYHQ/s640/rxt-search.png)


> whether you plan to have a feature that excludes some attributes at the time of generation because some fixed attributes do not need to be bound to the interface.

I've added #265 as a way to track this separate request.

My hope was that it should be quick and easy to remove any generated element that you don't need but having a way to exclude them is a nice addition. If generating a lot of XAML and the code is already suitably attributed this could be worth the time to configure generation mappings accordingly.

> I sincerely want a way to generate buttons and bind commands even if this is optional.

This will come.
Are you using a Framework to automatically map the event to the method or using a Behavior? I know Caliburn & Prism have this built in but wondered if there's other scenarios to be aware of.

Public methods that take no parameters will be easy to identify and generate the XAML for but those taking parameters will be harder to handle. 
Further investigation is needed before this can be fully spec'd but I have some ideas.  If you can share examples of the methods you have and what you'd like to see generated, this may help. Thanks.

**Comment by mrlacey** [comment]
> I also have a suggestion that I hope this extension will add shortcuts to allow developers to quickly generate XAML by selecting the attributes and then pressing the shortcuts before copying.

I'm not sure what you're asking here.
You can already select **properties** and generate the XAML for them.

![](https://github.com/microsoft/Rapid-XAML-Toolkit/raw/dev/docs/Assets/Copy-Selection-To-Clipboard.gif)

**Comment by XuJin186** [comment]
> > 我也有建议，我希望此扩展将添加快捷方式，以允许开发人员通过选择属性，然后在复制之前按快捷方式来快速生成XAML。
> 
> 我不确定您在这里问什么。
> 您已经可以选择**属性**并为其生成XAML。
> 
> ![](https://github.com/microsoft/Rapid-XAML-Toolkit/raw/dev/docs/Assets/Copy-Selection-To-Clipboard.gif)

Yes, your operation is really achievable. What I said is that shortcut keys can be used after selection

> > I also have a suggestion that I hope this extension will add shortcuts to allow developers to quickly generate XAML by selecting the attributes and then pressing the shortcuts before copying.
> 
> I'm not sure what you're asking here.
> You can already select **properties** and generate the XAML for them.
> 
> ![](https://github.com/microsoft/Rapid-XAML-Toolkit/raw/dev/docs/Assets/Copy-Selection-To-Clipboard.gif)

Yes, your operation is really achievable. What I said is that shortcut keys can be used after selection

**Comment by XuJin186** [comment]
Thank you for your answer, today's network speed may not be good, so I have been downloading failure, I personally feel that attribute filter is necessary. For example, if the model inherits INotifyDataErrorInfo, the HasError attribute will appear. I don't think it's necessary to map this attribute.

**Comment by mrlacey** [comment]
> For example, if the model inherits INotifyDataErrorInfo, the HasError attribute will appear. I don't think it's necessary to map this attribute.

If a base class (or interface) has a property that you never want to produce XAML for this is already possible without attributes.

for example, if the base class included `public bool HasErrors { get; set; }` this could be excluded from all generation with a mapping like this:

![image](https://user-images.githubusercontent.com/189547/65374855-7a792980-dc86-11e9-8ba2-eab417c1b1e2.png)

**Comment by XuJin186** [comment]
I'm sorry, but I'd like to ask you one more thing.

![TIM截图20190921234155](https://user-images.githubusercontent.com/43058612/65375554-7e7a6b00-dcc9-11e9-891e-14cd34409c2d.png)
![TIM截图20190921234206](https://user-images.githubusercontent.com/43058612/65375555-80442e80-dcc9-11e9-8f7b-04c1e0202252.png)
![TIM截图20190921234227](https://user-images.githubusercontent.com/43058612/65375556-81755b80-dcc9-11e9-8b67-23bc77d8a9ef.png)
I want to use features for localization, but now there are exception configurations and exception information as shown in the figure.

**Comment by mrlacey** [comment]
> I want to use features for localization, but now there are exception configurations and exception information as shown in the figure.

Looks like you've found a bug in the attribute parsing code. Working on it now.

**Comment by mrlacey** [comment]
> > I want to use features for localization, but now there are exception configurations and exception information as shown in the figure.
> 
> Looks like you've found a bug in the attribute parsing code. Working on it now.

version 0.3.7 is now in the marketplace and (among other things) it includes a fix for this issue.

**Comment by XuJin186** [comment]
I seem to have another problem. Please take a look at the screenshot
![TIM截图20190922140232](https://user-images.githubusercontent.com/43058612/65383053-bde49e00-dd41-11e9-9289-00eb78e35628.png)

**Comment by XuJin186** [comment]
Also, I want to generate Xaml through Display, but it has been unsuccessful. Can you provide use cases?`  public int ID { get; set; }
        [MaxLength(200)]
        public string Name { get; set; }
        public string shi { get; set; }
        public string shi1 { get; set; }
        public string sh2i { get; set; }
        [Display(Name = "Test")]
        public string shi3 { get; set; }`

The configuration file is
`<ui:FormItem $att:Label:Display="[1]"$ ><ui:TextBox Text="{Binding $name$}" $att:MaxLength: MaxLength="[1]"$/></ui:FormItem>`

XAML:
`<ui:Form>
    <ui:FormItem Label="ID">
        <ui:IntegerIntUpDown Value="{Binding Path=ID}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding Name}" MaxLength="200" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding shi}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding shi1}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding sh2i}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding shi3}" />
    </ui:FormItem>
</ui:Form>`
It does not seem to have succeeded.

**Comment by mrlacey** [comment]
@daxianji007 The parameter in the attribute markup is wrong.
The output should be

```xml
<ui:FormItem $att:Display:Label="[1]"$ ><ui:TextBox Text="{Binding $name$}" $att:MaxLength: MaxLength="[1]"$/></ui:FormItem>
```

**Comment by XuJin186** [comment]
Yeah, I'm sorry for my mistake, but when I inherit another class, I generate a mistake.
`[21:17:06.956]  Detected project type as 'WPF'.
[21:17:07.404]  Detected project type as 'WPF'.
[21:17:07.409]  Detected project type as 'WPF'.
[21:17:07.498]  Detected project type as 'WPF'.
[21:17:07.550]  Detected project type as 'WPF'.
[21:17:07.756]  RapidXamlDropHandler
[21:17:07.985]  Dropping 'H:\WPF控件\WPFControl\WPFControlTest\Class1.cs' onto view.
[21:17:07.989]  Using profile 'WPF Form'.
[21:17:07.992]  正在分析 C# 代码。(v0.3.7.0)
[21:17:07.995]  正在获取单个项目的输出。
[21:17:07.997]  正在获取类的输出。
[21:17:08.003]  已将属性标识为: 名称为“ID”，类型为“int”，IsReadOnly 为“False”。
[21:17:08.005]  已找到子属性“ID”。
[21:17:08.008]  已将属性标识为: 名称为“Name”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.010]  已找到子属性“Name”。
[21:17:08.012]  已将属性标识为: 名称为“shi”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.015]  已找到子属性“shi”。
[21:17:08.017]  已将属性标识为: 名称为“shi1”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.020]  已找到子属性“shi1”。
[21:17:08.023]  已将属性标识为: 名称为“sh2i”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.025]  已找到子属性“sh2i”。
[21:17:08.032]  已将属性标识为: 名称为“shi3”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.034]  已找到子属性“shi3”。
[21:17:08.037]  已将属性标识为: 名称为“DisplayName”，类型为“string”，IsReadOnly 为“False”。
[21:17:08.040]  已找到子属性“DisplayName”。
[21:17:08.042]  已将属性标识为: 名称为“State”，类型为“ScreenState”，IsReadOnly 为“False”。
[21:17:08.045]  已找到子属性“State”。
[21:17:08.047]  已将属性标识为: 名称为“ScreenState”，类型为“ScreenState”，IsReadOnly 为“False”。
[21:17:08.050]  已找到子属性“ScreenState”。
[21:17:08.055]  已将属性标识为: 名称为“IsActive”，类型为“bool”，IsReadOnly 为“True”。
[21:17:08.057]  已找到子属性“IsActive”。
[21:17:08.060]  已将属性标识为: 名称为“View”，类型为“UIElement”，IsReadOnly 为“True”。
[21:17:08.062]  已找到子属性“View”。
[21:17:08.065]  已将属性标识为: 名称为“Parent”，类型为“object”，IsReadOnly 为“False”。
[21:17:08.067]  已找到子属性“Parent”。
[21:17:08.070]  Exception
[21:17:08.073]  =========
[21:17:08.075]  未将对象引用设置到对象的实例。
[21:17:08.081]  RapidXamlToolkitExt
[21:17:08.084]     在 RapidXamlToolkit.Parsers.CSharpParser.GetPropertyDetails(PropertyDeclarationSyntax propertyDeclaration, SemanticModel semModel) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 372
   在 RapidXamlToolkit.Parsers.CSharpParser.GetAllPublicProperties(ITypeSymbol typeSymbol, SemanticModel semModel) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 251
   在 RapidXamlToolkit.Parsers.CSharpParser.GetSingleItemOutput(SyntaxNode documentRoot, SemanticModel semModel, Int32 caretPosition) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 55
   在 RapidXamlToolkit.DragDrop.DropHandlerLogic.<ExecuteAsync>d__5.MoveNext() 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\DragDrop\DropHandlerLogic.cs:行号 59
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 RapidXamlToolkit.DragDrop.RapidXamlDropHandler.<>c__DisplayClass8_0.<<HandleDataDropped>b__0>d.MoveNext() 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\DragDrop\RapidXamlDropHandler.cs:行号 56`

**Comment by XuJin186** [comment]
Excuse me. Is this my configuration problem?
configuration file：
`<DataGridTextColumn $att:Display:Header="[1]"$    Binding="{Binding $name$}"   Width="*"/>`
XAML:
` <ui:DataGrid ItemsSource="{Binding Class1s}">
           <ui:DataGrid.Columns>
               <DataGridTextColumn Binding="{Binding ID}" Width="*" />
               <DataGridTextColumn Binding="{Binding Name}" Width="*" />
               <DataGridTextColumn Binding="{Binding shi}" Width="*" />
               <DataGridTextColumn Binding="{Binding shi1}" Width="*" />
               <DataGridTextColumn Binding="{Binding sh2i}" Width="*" />
               <DataGridTextColumn Binding="{Binding shi3}" Width="*" />
           </ui:DataGrid.Columns>
       </ui:DataGrid>`
You see, there is no Header attribute.

**Comment by mrlacey** [comment]
> Excuse me. Is this my configuration problem?
> configuration file：
> `<DataGridTextColumn $att:Display:Header="[1]"$ Binding="{Binding $name$}" Width="*"/>`
> XAML:
> ` <ui:DataGrid ItemsSource="{Binding Class1s}"> <ui:DataGrid.Columns> <DataGridTextColumn Binding="{Binding ID}" Width="*" /> <DataGridTextColumn Binding="{Binding Name}" Width="*" /> <DataGridTextColumn Binding="{Binding shi}" Width="*" /> <DataGridTextColumn Binding="{Binding shi1}" Width="*" /> <DataGridTextColumn Binding="{Binding sh2i}" Width="*" /> <DataGridTextColumn Binding="{Binding shi3}" Width="*" /> </ui:DataGrid.Columns> </ui:DataGrid>`
> You see, there is no Header attribute.

This looks like the same issue as #271 where attributes on properties aren't detected when using **$subprops$**. I'll prioritize this.

**Comment by XuJin186** [comment]
> Yeah, I'm sorry for my mistake, but when I inherit another class, I generate a mistake.
> `[21:17:06.956] Detected project type as 'WPF'. [21:17:07.404] Detected project type as 'WPF'. [21:17:07.409] Detected project type as 'WPF'. [21:17:07.498] Detected project type as 'WPF'. [21:17:07.550] Detected project type as 'WPF'. [21:17:07.756] RapidXamlDropHandler [21:17:07.985] Dropping 'H:\WPF控件\WPFControl\WPFControlTest\Class1.cs' onto view. [21:17:07.989] Using profile 'WPF Form'. [21:17:07.992] 正在分析 C# 代码。(v0.3.7.0) [21:17:07.995] 正在获取单个项目的输出。 [21:17:07.997] 正在获取类的输出。 [21:17:08.003] 已将属性标识为: 名称为“ID”，类型为“int”，IsReadOnly 为“False”。 [21:17:08.005] 已找到子属性“ID”。 [21:17:08.008] 已将属性标识为: 名称为“Name”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.010] 已找到子属性“Name”。 [21:17:08.012] 已将属性标识为: 名称为“shi”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.015] 已找到子属性“shi”。 [21:17:08.017] 已将属性标识为: 名称为“shi1”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.020] 已找到子属性“shi1”。 [21:17:08.023] 已将属性标识为: 名称为“sh2i”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.025] 已找到子属性“sh2i”。 [21:17:08.032] 已将属性标识为: 名称为“shi3”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.034] 已找到子属性“shi3”。 [21:17:08.037] 已将属性标识为: 名称为“DisplayName”，类型为“string”，IsReadOnly 为“False”。 [21:17:08.040] 已找到子属性“DisplayName”。 [21:17:08.042] 已将属性标识为: 名称为“State”，类型为“ScreenState”，IsReadOnly 为“False”。 [21:17:08.045] 已找到子属性“State”。 [21:17:08.047] 已将属性标识为: 名称为“ScreenState”，类型为“ScreenState”，IsReadOnly 为“False”。 [21:17:08.050] 已找到子属性“ScreenState”。 [21:17:08.055] 已将属性标识为: 名称为“IsActive”，类型为“bool”，IsReadOnly 为“True”。 [21:17:08.057] 已找到子属性“IsActive”。 [21:17:08.060] 已将属性标识为: 名称为“View”，类型为“UIElement”，IsReadOnly 为“True”。 [21:17:08.062] 已找到子属性“View”。 [21:17:08.065] 已将属性标识为: 名称为“Parent”，类型为“object”，IsReadOnly 为“False”。 [21:17:08.067] 已找到子属性“Parent”。 [21:17:08.070] Exception [21:17:08.073] ========= [21:17:08.075] 未将对象引用设置到对象的实例。 [21:17:08.081] RapidXamlToolkitExt [21:17:08.084] 在 RapidXamlToolkit.Parsers.CSharpParser.GetPropertyDetails(PropertyDeclarationSyntax propertyDeclaration, SemanticModel semModel) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 372 在 RapidXamlToolkit.Parsers.CSharpParser.GetAllPublicProperties(ITypeSymbol typeSymbol, SemanticModel semModel) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 251 在 RapidXamlToolkit.Parsers.CSharpParser.GetSingleItemOutput(SyntaxNode documentRoot, SemanticModel semModel, Int32 caretPosition) 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\Parsers\CSharpParser.cs:行号 55 在 RapidXamlToolkit.DragDrop.DropHandlerLogic.<ExecuteAsync>d__5.MoveNext() 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\DragDrop\DropHandlerLogic.cs:行号 59 --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 RapidXamlToolkit.DragDrop.RapidXamlDropHandler.<>c__DisplayClass8_0.<<HandleDataDropped>b__0>d.MoveNext() 位置 C:\Users\matt\Documents\GitHub\mrlacey-RXT\VSIX\RapidXamlToolkit\DragDrop\RapidXamlDropHandler.cs:行号 56`

What do you think is the reason for this mistake?

**Comment by mrlacey** [comment]
> What do you think is the reason for this mistake?

It's to do with a lack of proper support for attributes without parameters. I'm working on a fix right now.

**Comment by mrlacey** [comment]
> Yeah, I'm sorry for my mistake 

These aren't your mistakes. Your finding a bunch of bugs and ways the code can be improved to make identifying possible issues.

Thank you so much for taking the time to report what you're finding. Together we can make this better for everyone.

**Comment by XuJin186** [comment]
> > Yeah, I'm sorry for my mistake
> 
> These aren't your mistakes. Your finding a bunch of bugs and ways the code can be improved to make identifying possible issues.
> 
> Thank you so much for taking the time to report what you're finding. Together we can make this better for everyone.

Yes, you are right. But now I have two more needs.

1. When I have a Class1 attribute in my ViewModel, the Xaml generated when I select it should contain class grouping.
Code：`   public Class1 Class1 { get; set; }`
Xaml：`   <ui:FormItem Label="Class1.ID">
        <ui:IntegerIntUpDown Value="{Binding Path=Class1.ID}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding Class1.Name}" MaxLength="200" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding Class1.shi}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding Class1.shi1}" />
    </ui:FormItem>
    <ui:FormItem>
        <ui:TextBox Text="{Binding Class1.sh2i}" />
    </ui:FormItem>
    <ui:FormItem Label="Test">
        <ui:TextBox Text="{Binding Class1.shi3}" />
    </ui:FormItem>`
My class grouping is ui: Form， So what I want to generate is
` <ui:Form>
     <ui:FormItem Label="ID">
         <ui:IntegerIntUpDown Value="{Binding Path=ID}" />
     </ui:FormItem>
     <ui:FormItem>
         <ui:TextBox Text="{Binding Name}" MaxLength="200" />
     </ui:FormItem>
     <ui:FormItem>
         <ui:TextBox Text="{Binding shi}" />
     </ui:FormItem>
     <ui:FormItem>
         <ui:TextBox Text="{Binding shi1}" />
     </ui:FormItem>
     <ui:FormItem>
         <ui:TextBox Text="{Binding sh2i}" />
     </ui:FormItem>
     <ui:FormItem Label="是我的">
         <ui:TextBox Text="{Binding shi3}" />
     </ui:FormItem>
 </ui:Form>`
Although I know that you can use Class drag-and-drop, it's not beautiful.

2.I sincerely hope that you can add shortcuts to let us develop quickly.
![TIM截图20190924102200](https://user-images.githubusercontent.com/43058612/65476386-564f5f80-deb5-11e9-8913-f0fa4b5dea8f.png)
That's probably the way it is.



Excuse me for my poor English

**Comment by mrlacey** [comment]
> 2.I sincerely hope that you can add shortcuts to let us develop quickly.

You can add these yourself to any command.

Go to: **Tools** > **Options** and select **Environment** > **Keyboard**

Search for the command you want (e.g. search "rapid")

select the relevant command.

Put the cursor in the box highlighted below and press the keys you want to assign.

![image](https://user-images.githubusercontent.com/189547/65631823-3e203300-dfd0-11e9-81ec-3f844e3e49a1.png)

You can then use the assigned shortcut keys.

![image](https://user-images.githubusercontent.com/189547/65631706-f7cad400-dfcf-11e9-9f8a-dadf0e15a8d0.png)

**Comment by mrlacey** [comment]
> When I have a Class1 attribute in my ViewModel, the Xaml generated when I select it should contain class grouping.

When you highlight the code it just gets the properties within the selection.

If you want the whole class, put the cursor on the class name and select 'Rapid XAML > Copy to Clipboard' and then you'll get the class grouping.

**Comment by mrlacey** [comment]
> > What do you think is the reason for this mistake?
> 
> It's to do with a lack of proper support for attributes without parameters. I'm working on a fix right now.

This took longer than expected (sorry) but also led me to a number of other scenarios where code would fail to generate the correct XAML or cause an error in the attempt.
These have all been addressed in the 0.3.8 release which has just been uploaded to the marketplace.

**Comment by XuJin186** [comment]
> > When I have a Class1 attribute in my ViewModel, the Xaml generated when I select it should contain class grouping.
> 
> When you highlight the code it just gets the properties within the selection.
> 
> If you want the whole class, put the cursor on the class name and select 'Rapid XAML > Copy to Clipboard' and then you'll get the class grouping.

Yes, you can, but you forgot one thing. That's why I want View Binding in a ViewModel. The generated XAML should be {Binding Model.ID} instead of {Binding ID}

**Comment by XuJin186** [comment]
> > > What do you think is the reason for this mistake?
> > 
> > 
> > It's to do with a lack of proper support for attributes without parameters. I'm working on a fix right now.
> 
> This took longer than expected (sorry) but also led me to a number of other scenarios where code would fail to generate the correct XAML or cause an error in the attempt.
> These have all been addressed in the 0.3.8 release which has just been uploaded to the marketplace.

Are you not supporting WPF?
configure：

`<DataGridTextColumn  Binding="{Binding $name$}"   Width="*"  $att:Display:Header="[1]"$/>`
Code：
```
    public class MyClass1
    {
        [Display(Name = "This Is ID")]
        public int ID { get; set; }

        [Display(Name = "This Is Name")]
        public string Name { get; set; }
    }
```
Error in Generation
[13:54:40.489]  Output contains placeholder for attribute 'Display'
[13:54:40.491]  Attribute not found on property.

**Comment by mrlacey** [comment]
> Yes, you can, but you forgot one thing. That's why I want View Binding in a ViewModel. The generated XAML should be {Binding Model.ID} instead of {Binding ID}

How to get this depends on the class you are generating the content from.


If you have a class like

```cs
class MyViewModel
{
    public MyModel Model { get; set; }
}
```

then using output like `<TextBlock Text="{Binding $name$}">` this will give you 
```
<TextBlock Text="{Binding Model.Id}">
<TextBlock Text="{Binding Model.Name}">
....
```

If you have a class like

```cs
class MyViewModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    ...
}
```

and you want `Model.` to appear before the property names in the binding then you'll need to add this to the output template. e.g.  `<TextBlock Text="{Binding Model.$name$}">`

This is because the XAML Generation does not know the DataContext of where the XAML will be placed (and there are many different ways it could be set) and so can't add anything to the generation automatically.

**Comment by XuJin186** [comment]
Generally speaking, if there is a Model in ViewModel, it is used for CURD. This is the perfect way to use EF.

**Comment by mrlacey** [comment]
> > > > What do you think is the reason for this mistake?
> > > 
> > > 
> > > It's to do with a lack of proper support for attributes without parameters. I'm working on a fix right now.
> > 
> > 
> > This took longer than expected (sorry) but also led me to a number of other scenarios where code would fail to generate the correct XAML or cause an error in the attempt.
> > These have all been addressed in the 0.3.8 release which has just been uploaded to the marketplace.
> 
> Are you not supporting WPF?
> configure：
> 
> `<DataGridTextColumn Binding="{Binding $name$}" Width="*" $att:Display:Header="[1]"$/>`
> Code：
> 
> ```
>     public class MyClass1
>     {
>         [Display(Name = "This Is ID")]
>         public int ID { get; set; }
> 
>         [Display(Name = "This Is Name")]
>         public string Name { get; set; }
>     }
> ```
> 
> Error in Generation
> [13:54:40.489] Output contains placeholder for attribute 'Display'
> [13:54:40.491] Attribute not found on property.

WPF is supported.
This should work.
I'm investigating why it's not.

**Comment by mrlacey** [comment]
> Generally speaking, if there is a Model in ViewModel, it is used for CURD. This is the perfect way to use EF.

That may be but not everyone uses EF and conventions like this vary between platforms, frameworks, and ORMs.
The default profiles are deliberately generic so as not to favor one platform/framework/whatever but the configurable ability should allow anyone to adjust them as they need or their platform/framework/convention prefers.

**Comment by XuJin186** [comment]
You're not right about that. As you can see, most projects deal with databases. It's normal to have models. Now that you have entities, it's unreasonable to go to ViewModel to create new properties to bind. So most projects still bind models, so I think this proposal is right.

**Comment by mrlacey** [comment]
> You're not right about that. As you can see, most projects deal with databases. It's normal to have models. Now that you have entities, it's unreasonable to go to ViewModel to create new properties to bind. So most projects still bind models, so I think this proposal is right.

We're going to have to agree to disagree on this. It might be that in your experience of building WPF apps that most use databases and most of them use Entity Framework. However, this is not my experience and it's certainly not the case for UWP and Xamarin.Forms apps.
I'm not sure which proposal you're explicitly referring too but I don't see a strong argument for doing anything specific to WPF that is based on an assumption regarding databases and ORMs.

**Comment by XuJin186** [comment]
OK.

**Comment by mrlacey** [comment]
> WPF is supported.
> This should work.
> I'm investigating why it's not.

After much investigation it seems that I messed up the 0.3.8 release and that functionality didn't go in correctly. I've just released version 0.3.9 which definitely supports the use of attribute based templates for sub properties.

**Comment by XuJin186** [comment]
OK, thanks.
